# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish pipeline

on:
    workflow_dispatch:
    push:
        branches: [master]

jobs:
    publish:
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
            pull-requests: write
            issues: write
        steps:
            - uses: actions/setup-node@v2
              with:
                  node-version: 20
                  registry-url: https://npm.pkg.github.com/
            - uses: actions/checkout@v2
            - run: npm i -g @kenan/npm-cli-login
            - run: npm ci
            - name: Run tests
              run: npm run build
            - run: npm run test
            - name: Nexus login
              run: npm-cli-login -u ${X3_NEXUS_USERNAME} -p ${X3_NEXUS_PASSWORD} -e sagex3ci@sage.com -r https://repository.sagex3.com:8443/repository/x3-npm-hosted --scope @sage
            - name: Release package
              run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  X3_NEXUS_PASSWORD: ${{ secrets.X3_NEXUS_PASSWORD }}
                  X3_NEXUS_USERNAME: ${{ secrets.X3_NEXUS_USERNAME }}
