# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish pipeline

on:
    workflow_dispatch:
    push:
        branches: [master]

jobs:
    publish:
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
            pull-requests: write
            issues: write
        steps:
            - uses: actions/setup-node@v2
              with:
                  node-version: 20
                  registry-url: https://npm.pkg.github.com/
            - uses: actions/checkout@v2
            - run: npm ci
            - name: Run tests
              run: npm run build
            - run: npm run test
            - name: Release package
              run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    copy:
        needs: publish
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
            pull-requests: write
            issues: write
        steps:
            - uses: actions/setup-node@v2
              with:
                  node-version: 14
            - run: npm i -g npm-copy
            - name: Copy package to X3 Nexus Repository
              run: npm-copy --from https://npm.pkg.github.com/ --from-token "${NODE_AUTH_TOKEN}" --to https://repository.sagex3.com:8443/repository/x3-npm-hosted --to-username "${X3_NEXUS_USERNAME}" --to-password "${X3_NEXUS_PASSWORD}" --to-email bence.laky@sage.com %40sage%2Flokijs
              env:
                  X3_NEXUS_PASSWORD: ${{ secrets.X3_NEXUS_PASSWORD }}
                  X3_NEXUS_USERNAME: ${{ secrets.X3_NEXUS_USERNAME }}
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
